name: "dbt_learning"
version: "1.0.0"
config-version: 2

profile: "my_new_project"

model-paths:
  - "models"

analysis-paths:
  - "analyses"

test-paths:
  - "tests"

seed-paths:
  - "seeds"

macro-paths:
  - "macros"

snapshot-paths:
  - "snapshots"

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_learning:
    +database: PC_DBT_DB
    staging:
      +materialized: view

    intermediate:
      +materialized: ephemeral

    marts:
      +materialized: table