# name: "dbt_learning"
name: "nathan_dbt_project"
version: "1.0.0"
config-version: 2

profile: "my_new_project"

vars:
   wrk_schema: BRONZE
   file_format_csv: MYNEWDB.BRONZE.MY_CSV_FORMAT
   purge_status: FALSE
   # why does it have a slash
   stage_name: MYNEWDB.BRONZE.s3_test_stage/
   rawhist_db: MYNEWDB

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  nathan_dbt_workshop:
    +database: PC_DBT_DB
    silver:
        +schema: silver
        +materialized: table
    gold:
        +schema: gold
        +materialized: view